import Head from "next/head"
import DataTable from "src/components/DataTable/DataTable"
import TitleBar from "src/components/TitleBar/TitleBar"

export default function Home() {
  return (
    <>
      <Head>
        <title>Codemask Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <TitleBar /> */}
      {/* <DataTable /> */}
    </>
  )
}
